/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aparcamiento.parkings;

import aparcamiento.servicios.*;
import javax.swing.JDialog;

/**
 *
 * @author david
 */
public class Amma extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Amma() {
        lib = new boolean[33];
        for (int i = 0; i < 33; i++) {
            lib[i] = true;
        }
        initComponents();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Amma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Amma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Amma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Amma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Amma().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        materialPanel1 = new de.craften.ui.swingmaterial.MaterialPanel();
        jLabel2 = new javax.swing.JLabel();
        planta0 = new de.craften.ui.swingmaterial.MaterialButton();
        planta1 = new de.craften.ui.swingmaterial.MaterialButton();
        planta2 = new de.craften.ui.swingmaterial.MaterialButton();
        planta3 = new de.craften.ui.swingmaterial.MaterialButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        p3 = new javax.swing.JButton();
        p2 = new javax.swing.JButton();
        p1 = new javax.swing.JButton();
        p4 = new javax.swing.JButton();
        p10 = new javax.swing.JButton();
        p14 = new javax.swing.JButton();
        p13 = new javax.swing.JButton();
        p12 = new javax.swing.JButton();
        p15 = new javax.swing.JButton();
        p16 = new javax.swing.JButton();
        p17 = new javax.swing.JButton();
        parking = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        atras = new de.craften.ui.swingmaterial.MaterialButton();
        gasolineraButton = new de.craften.ui.swingmaterial.MaterialButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Parking \"Amma\"");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 400, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 100));

        materialPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setText("Seleccione la planta :");
        materialPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 180, 30));

        planta0.setBackground(new java.awt.Color(102, 102, 102));
        planta0.setText("Planta 0");
        planta0.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        planta0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planta0ActionPerformed(evt);
            }
        });
        materialPanel1.add(planta0, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 120, 60));

        planta1.setBackground(new java.awt.Color(204, 204, 204));
        planta1.setText("Planta 1");
        planta1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        planta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planta1ActionPerformed(evt);
            }
        });
        materialPanel1.add(planta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 120, 60));

        planta2.setBackground(new java.awt.Color(204, 204, 204));
        planta2.setText("Planta 2");
        planta2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        planta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planta2ActionPerformed(evt);
            }
        });
        materialPanel1.add(planta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 120, 60));

        planta3.setBackground(new java.awt.Color(204, 204, 204));
        planta3.setText("Planta 3");
        planta3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        planta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planta3ActionPerformed(evt);
            }
        });
        materialPanel1.add(planta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 120, 60));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setText("                 Precio");
        materialPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, -1, -1));

        jLabel17.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel17.setText("(2 adaptados)");
        materialPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, 80, 20));

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel18.setText("24");
        materialPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, -1, -1));

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel19.setText("                         Motos");
        materialPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, -1, -1));

        jLabel20.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel20.setText("            Ascensor");
        materialPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, -1, -1));

        jLabel21.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel21.setText("                 Baños");
        materialPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, -1, -1));

        jLabel22.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel22.setText("   Plazas totales");
        materialPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, -1, -1));

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel23.setText("                       Coches");
        materialPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, -1, -1));

        jLabel24.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel24.setText("Movilidad reducida");
        materialPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, -1, -1));

        jLabel25.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel25.setText("                 Familiares");
        materialPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, -1, -1));

        jLabel26.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel26.setText("      Localización");
        materialPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, -1, -1));

        jLabel27.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel27.setText("            Distancia");
        materialPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, -1, -1));

        jLabel28.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel28.setText("1300 m.");
        materialPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, -1, -1));

        jLabel29.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel29.setText("0,65 €/hora");
        materialPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, -1, -1));

        jLabel30.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel30.setText("24");
        materialPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, -1, -1));

        jLabel31.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel31.setText("72");
        materialPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, -1, -1));

        jLabel32.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel32.setText("12");
        materialPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, -1, -1));

        jLabel33.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel33.setText("132");
        materialPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, -1, -1));

        jLabel34.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel34.setText("SÍ");
        materialPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, -1, -1));

        jLabel35.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel35.setText("3");
        materialPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, -1, -1));

        jLabel36.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel36.setText("C/ de los Almendros, 8");
        materialPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 140, -1));
        materialPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 270, 10));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        materialPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, 20, 370));
        materialPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 270, 10));

        p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMinus.png"))); // NOI18N
        p3.setMnemonic(2);
        p3.setToolTipText("Libre");
        p3.setBorderPainted(false);
        p3.setContentAreaFilled(false);
        p3.setName("3"); // NOI18N
        p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 112, 53, 70));

        p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMinus.png"))); // NOI18N
        p2.setMnemonic(2);
        p2.setToolTipText("Libre");
        p2.setBorderPainted(false);
        p2.setContentAreaFilled(false);
        p2.setName("2"); // NOI18N
        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 112, 53, 70));

        p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMinus.png"))); // NOI18N
        p1.setMnemonic(2);
        p1.setToolTipText("Libre");
        p1.setBorderPainted(false);
        p1.setContentAreaFilled(false);
        p1.setName("1"); // NOI18N
        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 112, 53, 70));

        p4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); // NOI18N
        p4.setMnemonic(0);
        p4.setToolTipText("Libre");
        p4.setBorderPainted(false);
        p4.setContentAreaFilled(false);
        p4.setName("4"); // NOI18N
        p4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 112, 43, 70));

        p10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMotos.png"))); // NOI18N
        p10.setMnemonic(1);
        p10.setToolTipText("Libre");
        p10.setBorderPainted(false);
        p10.setContentAreaFilled(false);
        p10.setName("10"); // NOI18N
        p10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p10, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 112, 43, 35));

        p14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ocupadoMinus.png"))); // NOI18N
        p14.setMnemonic(2);
        p14.setToolTipText("Ocupado");
        p14.setBorderPainted(false);
        p14.setContentAreaFilled(false);
        p14.setName("14"); // NOI18N
        p14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p14, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 241, 53, 70));

        p13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMinus.png"))); // NOI18N
        p13.setMnemonic(2);
        p13.setToolTipText("Libre");
        p13.setBorderPainted(false);
        p13.setContentAreaFilled(false);
        p13.setName("13"); // NOI18N
        p13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p13, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 241, 53, 70));

        p12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMinus.png"))); // NOI18N
        p12.setMnemonic(2);
        p12.setToolTipText("Libre");
        p12.setBorderPainted(false);
        p12.setContentAreaFilled(false);
        p12.setName("12"); // NOI18N
        p12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p12, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 241, 53, 70));

        p15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMinus.png"))); // NOI18N
        p15.setMnemonic(2);
        p15.setToolTipText("Libre");
        p15.setBorderPainted(false);
        p15.setContentAreaFilled(false);
        p15.setName("12"); // NOI18N
        p15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p15, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 372, 53, 70));

        p16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMinus.png"))); // NOI18N
        p16.setMnemonic(2);
        p16.setToolTipText("Libre");
        p16.setBorderPainted(false);
        p16.setContentAreaFilled(false);
        p16.setName("13"); // NOI18N
        p16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p16, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 372, 53, 70));

        p17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMinus.png"))); // NOI18N
        p17.setMnemonic(2);
        p17.setToolTipText("Libre");
        p17.setBorderPainted(false);
        p17.setContentAreaFilled(false);
        p17.setName("14"); // NOI18N
        p17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p17, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 372, 53, 70));

        parking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pmediano.png"))); // NOI18N
        parking.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        materialPanel1.add(parking, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        getContentPane().add(materialPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 960, 490));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/gasolinera (1).png"))); // NOI18N
        jLabel10.setText(" Gasolinera");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/left-arrow.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));

        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        jPanel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 90, 80));

        gasolineraButton.setBackground(new java.awt.Color(0, 160, 160));
        gasolineraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gasolineraButtonActionPerformed(evt);
            }
        });
        jPanel1.add(gasolineraButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 220, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 92, 220, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_atrasActionPerformed

    private void gasolineraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gasolineraButtonActionPerformed
        JDialog gasolina = new Combustible(this, true);
        gasolina.setLocationRelativeTo(null);
        gasolina.setTitle("Surtidor de gasolina");
        gasolina.setVisible(true);
    }//GEN-LAST:event_gasolineraButtonActionPerformed


    private void accion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accion
        javax.swing.JButton aux = (javax.swing.JButton) evt.getSource();
        if (!aux.getToolTipText().equals("Ocupado")) {
            int i = Integer.parseInt(aux.getName());
            if (lib[i - 1]) {
                if (sel != null) {
                    libre(sel);
                    lib[Integer.parseInt(sel.getName()) - 1] = true;
                }
                reservado(aux);
                lib[i - 1] = false;
                sel = aux;
            } else {
                libre(aux);
                lib[i - 1] = true;
                sel = null;
            }
        }
    }//GEN-LAST:event_accion

    private void planta0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planta0ActionPerformed
        planta0.setBackground(new java.awt.Color(102, 102, 102));
        planta0.setFont(new java.awt.Font("Roboto Medium", 1, 14));
        planta1.setBackground(new java.awt.Color(204, 204, 204));
        planta1.setFont(new java.awt.Font("Roboto", 0, 14));
        planta2.setBackground(new java.awt.Color(204, 204, 204));
        planta2.setFont(new java.awt.Font("Roboto", 0, 14));        
        planta3.setBackground(new java.awt.Color(204, 204, 204));
        planta3.setFont(new java.awt.Font("Roboto", 0, 14));
    }//GEN-LAST:event_planta0ActionPerformed

    private void planta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planta1ActionPerformed
        planta1.setBackground(new java.awt.Color(102, 102, 102));
        planta1.setFont(new java.awt.Font("Roboto Medium", 1, 14));
        planta0.setBackground(new java.awt.Color(204, 204, 204));
        planta0.setFont(new java.awt.Font("Roboto", 0, 14));
        planta2.setBackground(new java.awt.Color(204, 204, 204));
        planta2.setFont(new java.awt.Font("Roboto", 0, 14));        
        planta3.setBackground(new java.awt.Color(204, 204, 204));
        planta3.setFont(new java.awt.Font("Roboto", 0, 14));
    }//GEN-LAST:event_planta1ActionPerformed

    private void planta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planta2ActionPerformed
        planta2.setBackground(new java.awt.Color(102, 102, 102));
        planta2.setFont(new java.awt.Font("Roboto Medium", 1, 14));
        planta1.setBackground(new java.awt.Color(204, 204, 204));
        planta1.setFont(new java.awt.Font("Roboto", 0, 14));
        planta0.setBackground(new java.awt.Color(204, 204, 204));
        planta0.setFont(new java.awt.Font("Roboto", 0, 14));        
        planta3.setBackground(new java.awt.Color(204, 204, 204));
        planta3.setFont(new java.awt.Font("Roboto", 0, 14));
    }//GEN-LAST:event_planta2ActionPerformed

    private void planta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planta3ActionPerformed
        planta3.setBackground(new java.awt.Color(102, 102, 102));
        planta3.setFont(new java.awt.Font("Roboto Medium", 1, 14));
        planta1.setBackground(new java.awt.Color(204, 204, 204));
        planta1.setFont(new java.awt.Font("Roboto", 0, 14));
        planta2.setBackground(new java.awt.Color(204, 204, 204));
        planta2.setFont(new java.awt.Font("Roboto", 0, 14));        
        planta0.setBackground(new java.awt.Color(204, 204, 204));
        planta0.setFont(new java.awt.Font("Roboto", 0, 14));
    }//GEN-LAST:event_planta3ActionPerformed

    private void libre(javax.swing.JButton but) {
        switch(but.getMnemonic()) {
            case 0: but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); break;
            case 1: but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMotos.png"))); break;
            case 2: but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMinus.png"))); break;
        }
        but.setToolTipText("Libre");
    }
    
    private void ocupado(javax.swing.JButton but) {
        switch(but.getMnemonic()) {
            case 0: but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ocupadoCoche.png"))); break;
            case 1: but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ocupadoMotos.png"))); break;
            case 2: but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ocupadoMinus.png"))); break;
        }
        but.setToolTipText("Ocupado");
    }
    
    private void reservado(javax.swing.JButton but) {
        System.out.print(but.getMnemonic());
        switch(but.getMnemonic()) {
            case 0: but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/reservadoCoche.png"))); break;
            case 1: but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/reservadoMotos.png"))); break;
            case 2: but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/reservadoMinus.png"))); break;
        }
        but.setToolTipText("Reservado");
    }
    
    private boolean[] lib;
    private javax.swing.JButton sel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.craften.ui.swingmaterial.MaterialButton atras;
    private de.craften.ui.swingmaterial.MaterialButton gasolineraButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private de.craften.ui.swingmaterial.MaterialPanel materialPanel1;
    private javax.swing.JButton p1;
    private javax.swing.JButton p10;
    private javax.swing.JButton p12;
    private javax.swing.JButton p13;
    private javax.swing.JButton p14;
    private javax.swing.JButton p15;
    private javax.swing.JButton p16;
    private javax.swing.JButton p17;
    private javax.swing.JButton p2;
    private javax.swing.JButton p3;
    private javax.swing.JButton p4;
    private javax.swing.JLabel parking;
    private de.craften.ui.swingmaterial.MaterialButton planta0;
    private de.craften.ui.swingmaterial.MaterialButton planta1;
    private de.craften.ui.swingmaterial.MaterialButton planta2;
    private de.craften.ui.swingmaterial.MaterialButton planta3;
    // End of variables declaration//GEN-END:variables
}
