/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aparcamiento.parkings;

/**
 *
 * @author david
 */
public class Leyenda extends javax.swing.JDialog {

    /**
     * Creates new form Registro
     *
     * @param parent
     * @param modal
     */
    public Leyenda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cancelarButton = new de.craften.ui.swingmaterial.MaterialButton();
        motos = new javax.swing.JLabel();
        minus = new javax.swing.JLabel();
        fam = new javax.swing.JLabel();
        libre = new javax.swing.JLabel();
        ocupado = new javax.swing.JLabel();
        reservado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setForeground(new java.awt.Color(0, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setMinimumSize(new java.awt.Dimension(340, 290));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("Leyenda");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 320, 33));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Significado de los distintos tipos y estados de las plazas:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 350, 33));

        cancelarButton.setBackground(new java.awt.Color(255, 51, 51));
        cancelarButton.setText("Atrás");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cancelarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 140, 70));

        motos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        motos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lMotos.png"))); // NOI18N
        motos.setText(" Moto");
        jPanel2.add(motos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 85, -1, -1));

        minus.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        minus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lMinus.png"))); // NOI18N
        jPanel2.add(minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 85, -1, -1));

        fam.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        fam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lFam.png"))); // NOI18N
        fam.setText("Familiar");
        jPanel2.add(fam, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 85, -1, -1));

        libre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        libre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lLibre.png"))); // NOI18N
        libre.setText("Libre");
        jPanel2.add(libre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        ocupado.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        ocupado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lOcupado.png"))); // NOI18N
        ocupado.setText("Ocupada");
        jPanel2.add(ocupado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        reservado.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        reservado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lReservado.png"))); // NOI18N
        reservado.setText("Reservada");
        jPanel2.add(reservado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("Movilidad");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 85, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("reducida");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 450, 250));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.craften.ui.swingmaterial.MaterialButton cancelarButton;
    private javax.swing.JLabel fam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel libre;
    private javax.swing.JLabel minus;
    private javax.swing.JLabel motos;
    private javax.swing.JLabel ocupado;
    private javax.swing.JLabel reservado;
    // End of variables declaration//GEN-END:variables
}
