/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aparcamiento.parkings;

import aparcamiento.servicios.*;
import javax.swing.JDialog;

/**
 *
 * @author david
 */
public class URJC extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public URJC() {
        lib = new boolean[34];
        for (int i = 0; i < 34; i++) {
            lib[i] = true;
        }
        initComponents();
        aux = materialPanel1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        atras = new de.craften.ui.swingmaterial.MaterialButton();
        gasolineraButton = new de.craften.ui.swingmaterial.MaterialButton();
        lavaderoButton = new de.craften.ui.swingmaterial.MaterialButton();
        nivelButton = new de.craften.ui.swingmaterial.MaterialButton();
        materialPanel1 = new de.craften.ui.swingmaterial.MaterialPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        p1 = new javax.swing.JButton();
        p2 = new javax.swing.JButton();
        p3 = new javax.swing.JButton();
        p4 = new javax.swing.JButton();
        p5 = new javax.swing.JButton();
        p6 = new javax.swing.JButton();
        p7 = new javax.swing.JButton();
        p8 = new javax.swing.JButton();
        p9 = new javax.swing.JButton();
        p10 = new javax.swing.JButton();
        p11 = new javax.swing.JButton();
        p12 = new javax.swing.JButton();
        p13 = new javax.swing.JButton();
        p14 = new javax.swing.JButton();
        p15 = new javax.swing.JButton();
        p16 = new javax.swing.JButton();
        p17 = new javax.swing.JButton();
        p18 = new javax.swing.JButton();
        p19 = new javax.swing.JButton();
        p20 = new javax.swing.JButton();
        p21 = new javax.swing.JButton();
        p22 = new javax.swing.JButton();
        p23 = new javax.swing.JButton();
        p24 = new javax.swing.JButton();
        p25 = new javax.swing.JButton();
        p26 = new javax.swing.JButton();
        p27 = new javax.swing.JButton();
        p28 = new javax.swing.JButton();
        p29 = new javax.swing.JButton();
        p30 = new javax.swing.JButton();
        p31 = new javax.swing.JButton();
        p32 = new javax.swing.JButton();
        p33 = new javax.swing.JButton();
        p34 = new javax.swing.JButton();
        parking = new javax.swing.JLabel();
        planta3 = new de.craften.ui.swingmaterial.MaterialButton();
        planta2 = new de.craften.ui.swingmaterial.MaterialButton();
        planta1 = new de.craften.ui.swingmaterial.MaterialButton();
        planta0 = new de.craften.ui.swingmaterial.MaterialButton();
        planta4 = new de.craften.ui.swingmaterial.MaterialButton();
        planta5 = new de.craften.ui.swingmaterial.MaterialButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Parking \"Universidad Rey Juan Carlos\"");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 630, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 100));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/gasolinera (1).png"))); // NOI18N
        jLabel3.setText(" Gasolinera");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lavadero-de-coches (1).png"))); // NOI18N
        jLabel4.setText(" Lavadero");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/presion (1).png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 220, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/aceite (1) (1).png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 245, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel7.setText("Nivel de aire");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel8.setText("y aceite");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/left-arrow.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));

        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        jPanel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 90, 80));

        gasolineraButton.setBackground(new java.awt.Color(0, 160, 160));
        gasolineraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gasolineraButtonActionPerformed(evt);
            }
        });
        jPanel1.add(gasolineraButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 220, 100));

        lavaderoButton.setBackground(new java.awt.Color(0, 160, 160));
        lavaderoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lavaderoButtonActionPerformed(evt);
            }
        });
        jPanel1.add(lavaderoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, 100));

        nivelButton.setBackground(new java.awt.Color(0, 160, 160));
        nivelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(nivelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 220, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 92, 220, 500));

        materialPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setText("Seleccione la planta :");
        materialPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 180, 30));

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel17.setText("                 Precio");
        materialPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, -1, -1));

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel18.setText("(4 adaptados)");
        materialPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 340, 80, 20));

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel19.setText("18");
        materialPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 200, -1, -1));

        jLabel20.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel20.setText("                         Motos");
        materialPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, -1, -1));

        jLabel21.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel21.setText("            Ascensor");
        materialPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, -1, -1));

        jLabel22.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel22.setText("                 Baños");
        materialPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, -1, -1));

        jLabel23.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel23.setText("   Plazas totales");
        materialPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, -1, -1));

        jLabel24.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel24.setText("                       Coches");
        materialPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, -1, -1));

        jLabel25.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel25.setText("Movilidad reducida");
        materialPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, -1, -1));

        jLabel26.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel26.setText("                 Familiares");
        materialPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, -1, -1));

        jLabel27.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel27.setText("      Localización");
        materialPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, -1, -1));

        jLabel28.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel28.setText("            Distancia");
        materialPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, -1, -1));

        jLabel29.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel29.setText("745 m.");
        materialPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, -1, -1));

        jLabel30.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel30.setText("0,86 €/hora");
        materialPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, -1, -1));

        jLabel31.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel31.setText("24");
        materialPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 260, -1, -1));

        jLabel32.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel32.setText("150");
        materialPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, -1, -1));

        jLabel33.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel33.setText("12");
        materialPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 230, -1, -1));

        jLabel34.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel34.setText("204");
        materialPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, -1, -1));

        jLabel35.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel35.setText("SÍ");
        materialPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, -1, -1));

        jLabel36.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel36.setText("5");
        materialPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 340, -1, -1));

        jLabel37.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel37.setText("C/ San Cipriano, 10");
        materialPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, 120, -1));
        materialPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 270, 10));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        materialPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, 20, 370));
        materialPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 270, 10));

        p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMinus.png"))); // NOI18N
        p1.setMnemonic(2);
        p1.setToolTipText("Libre");
        p1.setBorderPainted(false);
        p1.setContentAreaFilled(false);
        p1.setName("1"); // NOI18N
        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 112, 53, 70));

        p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMinus.png"))); // NOI18N
        p2.setMnemonic(2);
        p2.setToolTipText("Libre");
        p2.setBorderPainted(false);
        p2.setContentAreaFilled(false);
        p2.setName("2"); // NOI18N
        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 112, 53, 70));

        p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMinus.png"))); // NOI18N
        p3.setMnemonic(2);
        p3.setToolTipText("Libre");
        p3.setBorderPainted(false);
        p3.setContentAreaFilled(false);
        p3.setName("3"); // NOI18N
        p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 112, 53, 70));

        p4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); // NOI18N
        p4.setMnemonic(0);
        p4.setToolTipText("Libre");
        p4.setBorderPainted(false);
        p4.setContentAreaFilled(false);
        p4.setName("4"); // NOI18N
        p4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 112, 43, 70));

        p5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); // NOI18N
        p5.setMnemonic(0);
        p5.setToolTipText("Libre");
        p5.setBorderPainted(false);
        p5.setContentAreaFilled(false);
        p5.setName("5"); // NOI18N
        p5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 112, 43, 70));

        p6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); // NOI18N
        p6.setMnemonic(0);
        p6.setToolTipText("Libre");
        p6.setBorderPainted(false);
        p6.setContentAreaFilled(false);
        p6.setName("6"); // NOI18N
        p6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 112, 43, 70));

        p7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); // NOI18N
        p7.setMnemonic(0);
        p7.setToolTipText("Libre");
        p7.setBorderPainted(false);
        p7.setContentAreaFilled(false);
        p7.setName("7"); // NOI18N
        p7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 112, 43, 70));

        p8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); // NOI18N
        p8.setMnemonic(0);
        p8.setToolTipText("Libre");
        p8.setBorderPainted(false);
        p8.setContentAreaFilled(false);
        p8.setName("8"); // NOI18N
        p8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p8, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 112, 43, 70));

        p9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); // NOI18N
        p9.setMnemonic(0);
        p9.setToolTipText("Libre");
        p9.setBorderPainted(false);
        p9.setContentAreaFilled(false);
        p9.setName("9"); // NOI18N
        p9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p9, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 112, 43, 70));

        p10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); // NOI18N
        p10.setMnemonic(0);
        p10.setToolTipText("Libre");
        p10.setBorderPainted(false);
        p10.setContentAreaFilled(false);
        p10.setName("10"); // NOI18N
        p10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p10, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 112, 43, 70));

        p11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMinus.png"))); // NOI18N
        p11.setMnemonic(2);
        p11.setToolTipText("Libre");
        p11.setBorderPainted(false);
        p11.setContentAreaFilled(false);
        p11.setName("11"); // NOI18N
        p11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p11, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 241, 53, 70));

        p12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); // NOI18N
        p12.setMnemonic(0);
        p12.setToolTipText("Libre");
        p12.setBorderPainted(false);
        p12.setContentAreaFilled(false);
        p12.setName("12"); // NOI18N
        p12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p12, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 241, 43, 70));

        p13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); // NOI18N
        p13.setMnemonic(0);
        p13.setToolTipText("Libre");
        p13.setBorderPainted(false);
        p13.setContentAreaFilled(false);
        p13.setName("13"); // NOI18N
        p13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p13, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 241, 43, 70));

        p14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); // NOI18N
        p14.setMnemonic(0);
        p14.setToolTipText("Libre");
        p14.setBorderPainted(false);
        p14.setContentAreaFilled(false);
        p14.setName("14"); // NOI18N
        p14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 241, 43, 70));

        p15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); // NOI18N
        p15.setMnemonic(0);
        p15.setToolTipText("Libre");
        p15.setBorderPainted(false);
        p15.setContentAreaFilled(false);
        p15.setName("15"); // NOI18N
        p15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p15, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 241, 43, 70));

        p16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); // NOI18N
        p16.setMnemonic(0);
        p16.setToolTipText("Libre");
        p16.setBorderPainted(false);
        p16.setContentAreaFilled(false);
        p16.setName("16"); // NOI18N
        p16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p16, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 241, 43, 70));

        p17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); // NOI18N
        p17.setMnemonic(0);
        p17.setToolTipText("Libre");
        p17.setBorderPainted(false);
        p17.setContentAreaFilled(false);
        p17.setName("17"); // NOI18N
        p17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p17, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 241, 43, 70));

        p18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); // NOI18N
        p18.setMnemonic(0);
        p18.setToolTipText("Libre");
        p18.setBorderPainted(false);
        p18.setContentAreaFilled(false);
        p18.setName("18"); // NOI18N
        p18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p18, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 241, 43, 70));

        p19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); // NOI18N
        p19.setMnemonic(0);
        p19.setToolTipText("Libre");
        p19.setBorderPainted(false);
        p19.setContentAreaFilled(false);
        p19.setName("19"); // NOI18N
        p19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p19, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 241, 43, 70));

        p20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); // NOI18N
        p20.setMnemonic(0);
        p20.setToolTipText("Libre");
        p20.setBorderPainted(false);
        p20.setContentAreaFilled(false);
        p20.setName("20"); // NOI18N
        p20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p20, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 241, 43, 70));

        p21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMotos.png"))); // NOI18N
        p21.setMnemonic(1);
        p21.setToolTipText("Libre");
        p21.setBorderPainted(false);
        p21.setContentAreaFilled(false);
        p21.setName("21"); // NOI18N
        p21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p21, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 241, 43, 35));

        p22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMotos.png"))); // NOI18N
        p22.setMnemonic(1);
        p22.setToolTipText("Libre");
        p22.setBorderPainted(false);
        p22.setContentAreaFilled(false);
        p22.setName("22"); // NOI18N
        p22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p22, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 276, 43, 35));

        p23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMinus.png"))); // NOI18N
        p23.setMnemonic(2);
        p23.setToolTipText("Libre");
        p23.setBorderPainted(false);
        p23.setContentAreaFilled(false);
        p23.setName("23"); // NOI18N
        p23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p23, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 373, 53, 70));

        p24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); // NOI18N
        p24.setMnemonic(0);
        p24.setToolTipText("Libre");
        p24.setBorderPainted(false);
        p24.setContentAreaFilled(false);
        p24.setName("24"); // NOI18N
        p24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p24, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 373, 43, 70));

        p25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); // NOI18N
        p25.setMnemonic(0);
        p25.setToolTipText("Libre");
        p25.setBorderPainted(false);
        p25.setContentAreaFilled(false);
        p25.setName("25"); // NOI18N
        p25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p25, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 373, 43, 70));

        p26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); // NOI18N
        p26.setMnemonic(0);
        p26.setToolTipText("Libre");
        p26.setBorderPainted(false);
        p26.setContentAreaFilled(false);
        p26.setName("26"); // NOI18N
        p26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p26, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 373, 43, 70));

        p27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); // NOI18N
        p27.setMnemonic(0);
        p27.setToolTipText("Libre");
        p27.setBorderPainted(false);
        p27.setContentAreaFilled(false);
        p27.setName("27"); // NOI18N
        p27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p27, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 373, 43, 70));

        p28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); // NOI18N
        p28.setMnemonic(0);
        p28.setToolTipText("Libre");
        p28.setBorderPainted(false);
        p28.setContentAreaFilled(false);
        p28.setName("28"); // NOI18N
        p28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p28, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 373, 43, 70));

        p29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); // NOI18N
        p29.setMnemonic(0);
        p29.setToolTipText("Libre");
        p29.setBorderPainted(false);
        p29.setContentAreaFilled(false);
        p29.setName("29"); // NOI18N
        p29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p29, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 373, 43, 70));

        p30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); // NOI18N
        p30.setMnemonic(0);
        p30.setToolTipText("Libre");
        p30.setBorderPainted(false);
        p30.setContentAreaFilled(false);
        p30.setName("30"); // NOI18N
        p30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p30, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 373, 43, 70));

        p31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); // NOI18N
        p31.setMnemonic(0);
        p31.setToolTipText("Libre");
        p31.setBorderPainted(false);
        p31.setContentAreaFilled(false);
        p31.setName("31"); // NOI18N
        p31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p31, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 373, 43, 70));

        p32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png"))); // NOI18N
        p32.setMnemonic(0);
        p32.setToolTipText("Libre");
        p32.setBorderPainted(false);
        p32.setContentAreaFilled(false);
        p32.setName("32"); // NOI18N
        p32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p32, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 373, 43, 70));

        p33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMotos.png"))); // NOI18N
        p33.setMnemonic(1);
        p33.setToolTipText("Libre");
        p33.setBorderPainted(false);
        p33.setContentAreaFilled(false);
        p33.setName("33"); // NOI18N
        p33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p33, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 373, 43, 35));

        p34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMotos.png"))); // NOI18N
        p34.setMnemonic(1);
        p34.setToolTipText("Libre");
        p34.setBorderPainted(false);
        p34.setContentAreaFilled(false);
        p34.setName("34"); // NOI18N
        p34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        materialPanel1.add(p34, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 408, 43, 35));

        parking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pgrande.png"))); // NOI18N
        parking.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        materialPanel1.add(parking, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        planta3.setBackground(new java.awt.Color(204, 204, 204));
        planta3.setText("Planta 3");
        planta3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        planta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planta3ActionPerformed(evt);
            }
        });
        materialPanel1.add(planta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 120, 60));

        planta2.setBackground(new java.awt.Color(204, 204, 204));
        planta2.setText("Planta 2");
        planta2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        planta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planta2ActionPerformed(evt);
            }
        });
        materialPanel1.add(planta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 120, 60));

        planta1.setBackground(new java.awt.Color(204, 204, 204));
        planta1.setText("Planta 1");
        planta1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        planta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planta1ActionPerformed(evt);
            }
        });
        materialPanel1.add(planta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 120, 60));

        planta0.setBackground(new java.awt.Color(102, 102, 102));
        planta0.setText("Planta 0");
        planta0.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        planta0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planta0ActionPerformed(evt);
            }
        });
        materialPanel1.add(planta0, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 120, 60));

        planta4.setBackground(new java.awt.Color(204, 204, 204));
        planta4.setText("Planta 4");
        planta4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        planta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planta4ActionPerformed(evt);
            }
        });
        materialPanel1.add(planta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 120, 60));

        planta5.setBackground(new java.awt.Color(204, 204, 204));
        planta5.setText("Planta 5");
        planta5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        planta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planta5ActionPerformed(evt);
            }
        });
        materialPanel1.add(planta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 120, 60));

        getContentPane().add(materialPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 960, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_atrasActionPerformed

    private void gasolineraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gasolineraButtonActionPerformed
        Gasolinera g = new Gasolinera();
        getContentPane().remove(aux);
        aux = g.getPanel();
        getContentPane().add(aux, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 960, 490));
        pack();
    }//GEN-LAST:event_gasolineraButtonActionPerformed

    private void lavaderoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lavaderoButtonActionPerformed
        Lavadero g = new Lavadero();
        getContentPane().remove(aux);
        aux = g.getPanel();
        getContentPane().add(aux, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 960, 490));
        pack();
    }//GEN-LAST:event_lavaderoButtonActionPerformed

    private void nivelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelButtonActionPerformed
        Nivel g = new Nivel();
        getContentPane().remove(aux);
        aux = g.getPanel();
        getContentPane().add(aux, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 960, 490));
        pack();
    }//GEN-LAST:event_nivelButtonActionPerformed

    private void accion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accion
        javax.swing.JButton aux = (javax.swing.JButton) evt.getSource();
        if (!aux.getToolTipText().equals("Ocupado")) {
            int i = Integer.parseInt(aux.getName());
            if (lib[i - 1]) {
                if (sel != null) {
                    libre(sel);
                    lib[Integer.parseInt(sel.getName()) - 1] = true;
                }
                reservado(aux);
                lib[i - 1] = false;
                sel = aux;
            } else {
                libre(aux);
                lib[i - 1] = true;
                sel = null;
            }
        }
    }//GEN-LAST:event_accion

    private void planta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planta3ActionPerformed
        planta3.setBackground(new java.awt.Color(102, 102, 102));
        planta3.setFont(new java.awt.Font("Roboto Medium", 1, 14));
        planta1.setBackground(new java.awt.Color(204, 204, 204));
        planta1.setFont(new java.awt.Font("Roboto", 0, 14));
        planta2.setBackground(new java.awt.Color(204, 204, 204));
        planta2.setFont(new java.awt.Font("Roboto", 0, 14));
        planta0.setBackground(new java.awt.Color(204, 204, 204));
        planta0.setFont(new java.awt.Font("Roboto", 0, 14));
        planta4.setBackground(new java.awt.Color(204, 204, 204));
        planta4.setFont(new java.awt.Font("Roboto", 0, 14));
        planta5.setBackground(new java.awt.Color(204, 204, 204));
        planta5.setFont(new java.awt.Font("Roboto", 0, 14));
    }//GEN-LAST:event_planta3ActionPerformed

    private void planta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planta2ActionPerformed
        planta2.setBackground(new java.awt.Color(102, 102, 102));
        planta2.setFont(new java.awt.Font("Roboto Medium", 1, 14));
        planta1.setBackground(new java.awt.Color(204, 204, 204));
        planta1.setFont(new java.awt.Font("Roboto", 0, 14));
        planta0.setBackground(new java.awt.Color(204, 204, 204));
        planta0.setFont(new java.awt.Font("Roboto", 0, 14));
        planta3.setBackground(new java.awt.Color(204, 204, 204));
        planta3.setFont(new java.awt.Font("Roboto", 0, 14));
        planta4.setBackground(new java.awt.Color(204, 204, 204));
        planta4.setFont(new java.awt.Font("Roboto", 0, 14));
        planta5.setBackground(new java.awt.Color(204, 204, 204));
        planta5.setFont(new java.awt.Font("Roboto", 0, 14));
    }//GEN-LAST:event_planta2ActionPerformed

    private void planta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planta1ActionPerformed
        planta1.setBackground(new java.awt.Color(102, 102, 102));
        planta1.setFont(new java.awt.Font("Roboto Medium", 1, 14));
        planta0.setBackground(new java.awt.Color(204, 204, 204));
        planta0.setFont(new java.awt.Font("Roboto", 0, 14));
        planta2.setBackground(new java.awt.Color(204, 204, 204));
        planta2.setFont(new java.awt.Font("Roboto", 0, 14));
        planta3.setBackground(new java.awt.Color(204, 204, 204));
        planta3.setFont(new java.awt.Font("Roboto", 0, 14));
        planta4.setBackground(new java.awt.Color(204, 204, 204));
        planta4.setFont(new java.awt.Font("Roboto", 0, 14));
        planta5.setBackground(new java.awt.Color(204, 204, 204));
        planta5.setFont(new java.awt.Font("Roboto", 0, 14));
    }//GEN-LAST:event_planta1ActionPerformed

    private void planta0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planta0ActionPerformed
        planta0.setBackground(new java.awt.Color(102, 102, 102));
        planta0.setFont(new java.awt.Font("Roboto Medium", 1, 14));
        planta1.setBackground(new java.awt.Color(204, 204, 204));
        planta1.setFont(new java.awt.Font("Roboto", 0, 14));
        planta2.setBackground(new java.awt.Color(204, 204, 204));
        planta2.setFont(new java.awt.Font("Roboto", 0, 14));
        planta3.setBackground(new java.awt.Color(204, 204, 204));
        planta3.setFont(new java.awt.Font("Roboto", 0, 14));
        planta4.setBackground(new java.awt.Color(204, 204, 204));
        planta4.setFont(new java.awt.Font("Roboto", 0, 14));
        planta5.setBackground(new java.awt.Color(204, 204, 204));
        planta5.setFont(new java.awt.Font("Roboto", 0, 14));
    }//GEN-LAST:event_planta0ActionPerformed

    private void planta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planta4ActionPerformed
        planta4.setBackground(new java.awt.Color(102, 102, 102));
        planta4.setFont(new java.awt.Font("Roboto Medium", 1, 14));
        planta1.setBackground(new java.awt.Color(204, 204, 204));
        planta1.setFont(new java.awt.Font("Roboto", 0, 14));
        planta2.setBackground(new java.awt.Color(204, 204, 204));
        planta2.setFont(new java.awt.Font("Roboto", 0, 14));
        planta3.setBackground(new java.awt.Color(204, 204, 204));
        planta3.setFont(new java.awt.Font("Roboto", 0, 14));
        planta0.setBackground(new java.awt.Color(204, 204, 204));
        planta0.setFont(new java.awt.Font("Roboto", 0, 14));
        planta5.setBackground(new java.awt.Color(204, 204, 204));
        planta5.setFont(new java.awt.Font("Roboto", 0, 14));
    }//GEN-LAST:event_planta4ActionPerformed

    private void planta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planta5ActionPerformed
        planta5.setBackground(new java.awt.Color(102, 102, 102));
        planta5.setFont(new java.awt.Font("Roboto Medium", 1, 14));
        planta1.setBackground(new java.awt.Color(204, 204, 204));
        planta1.setFont(new java.awt.Font("Roboto", 0, 14));
        planta2.setBackground(new java.awt.Color(204, 204, 204));
        planta2.setFont(new java.awt.Font("Roboto", 0, 14));
        planta3.setBackground(new java.awt.Color(204, 204, 204));
        planta3.setFont(new java.awt.Font("Roboto", 0, 14));
        planta4.setBackground(new java.awt.Color(204, 204, 204));
        planta4.setFont(new java.awt.Font("Roboto", 0, 14));
        planta0.setBackground(new java.awt.Color(204, 204, 204));
        planta0.setFont(new java.awt.Font("Roboto", 0, 14));
    }//GEN-LAST:event_planta5ActionPerformed

    private void libre(javax.swing.JButton but) {
        switch (but.getMnemonic()) {
            case 0:
                but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche.png")));
                break;
            case 1:
                but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMotos.png")));
                break;
            case 2:
                but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMinus.png")));
                break;
        }
        but.setToolTipText("Libre");
    }

    private void ocupado(javax.swing.JButton but) {
        switch (but.getMnemonic()) {
            case 0:
                but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ocupadoCoche.png")));
                break;
            case 1:
                but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ocupadoMotos.png")));
                break;
            case 2:
                but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ocupadoMinus.png")));
                break;
        }
        but.setToolTipText("Ocupado");
    }

    private void reservado(javax.swing.JButton but) {
        switch (but.getMnemonic()) {
            case 0:
                but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/reservadoCoche.png")));
                break;
            case 1:
                but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/reservadoMotos.png")));
                break;
            case 2:
                but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/reservadoMinus.png")));
                break;
        }
        but.setToolTipText("Reservado");
    }

    private boolean[] lib;
    private javax.swing.JButton sel;
    private de.craften.ui.swingmaterial.MaterialPanel aux;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.craften.ui.swingmaterial.MaterialButton atras;
    private de.craften.ui.swingmaterial.MaterialButton gasolineraButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private de.craften.ui.swingmaterial.MaterialButton lavaderoButton;
    private de.craften.ui.swingmaterial.MaterialPanel materialPanel1;
    private de.craften.ui.swingmaterial.MaterialButton nivelButton;
    private javax.swing.JButton p1;
    private javax.swing.JButton p10;
    private javax.swing.JButton p11;
    private javax.swing.JButton p12;
    private javax.swing.JButton p13;
    private javax.swing.JButton p14;
    private javax.swing.JButton p15;
    private javax.swing.JButton p16;
    private javax.swing.JButton p17;
    private javax.swing.JButton p18;
    private javax.swing.JButton p19;
    private javax.swing.JButton p2;
    private javax.swing.JButton p20;
    private javax.swing.JButton p21;
    private javax.swing.JButton p22;
    private javax.swing.JButton p23;
    private javax.swing.JButton p24;
    private javax.swing.JButton p25;
    private javax.swing.JButton p26;
    private javax.swing.JButton p27;
    private javax.swing.JButton p28;
    private javax.swing.JButton p29;
    private javax.swing.JButton p3;
    private javax.swing.JButton p30;
    private javax.swing.JButton p31;
    private javax.swing.JButton p32;
    private javax.swing.JButton p33;
    private javax.swing.JButton p34;
    private javax.swing.JButton p4;
    private javax.swing.JButton p5;
    private javax.swing.JButton p6;
    private javax.swing.JButton p7;
    private javax.swing.JButton p8;
    private javax.swing.JButton p9;
    private javax.swing.JLabel parking;
    private de.craften.ui.swingmaterial.MaterialButton planta0;
    private de.craften.ui.swingmaterial.MaterialButton planta1;
    private de.craften.ui.swingmaterial.MaterialButton planta2;
    private de.craften.ui.swingmaterial.MaterialButton planta3;
    private de.craften.ui.swingmaterial.MaterialButton planta4;
    private de.craften.ui.swingmaterial.MaterialButton planta5;
    // End of variables declaration//GEN-END:variables
}
