/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aparcamiento.parkings;

import aparcamiento.servicios.*;
import java.awt.*;
import java.util.TimerTask;
import java.util.Timer;
import javax.swing.*;

/**
 *
 * @author david
 */
public class Villa extends javax.swing.JFrame implements Parking {

    /**
     * Creates new form Principal
     */
    public Villa() {
        getRootPane().setGlassPane(new JComponent() {
            public void paintComponent(Graphics g) {
                g.setColor(new Color(0, 0, 0, 100));
                g.fillRect(0, 0, getWidth(), getHeight());
                super.paintComponent(g);
            }
        });
        planta = "0";
        gas = new Gasolinera(this).getPanel();
        niv = new Nivel().getPanel();
        lib = new boolean[20];
        for (int i = 0; i < 20; i++) {
            lib[i] = true;
        }
        initComponents();
        aux = plazas;
        plazas.remove(cancelarButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        finalizarButton = new de.craften.ui.swingmaterial.MaterialButton();
        jLabel46 = new javax.swing.JLabel();
        tiempo = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        plazas = new de.craften.ui.swingmaterial.MaterialPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        planta0 = new de.craften.ui.swingmaterial.MaterialButton();
        planta1 = new de.craften.ui.swingmaterial.MaterialButton();
        planta2 = new de.craften.ui.swingmaterial.MaterialButton();
        p1 = new javax.swing.JButton();
        p2 = new javax.swing.JButton();
        p3 = new javax.swing.JButton();
        p4 = new javax.swing.JButton();
        p5 = new javax.swing.JButton();
        p6 = new javax.swing.JButton();
        p7 = new javax.swing.JButton();
        p8 = new javax.swing.JButton();
        p9 = new javax.swing.JButton();
        p10 = new javax.swing.JButton();
        p11 = new javax.swing.JButton();
        p12 = new javax.swing.JButton();
        p13 = new javax.swing.JButton();
        p14 = new javax.swing.JButton();
        p15 = new javax.swing.JButton();
        p16 = new javax.swing.JButton();
        p17 = new javax.swing.JButton();
        p18 = new javax.swing.JButton();
        p19 = new javax.swing.JButton();
        p20 = new javax.swing.JButton();
        parking = new javax.swing.JLabel();
        reservarButton = new de.craften.ui.swingmaterial.MaterialButton();
        jLabel12 = new javax.swing.JLabel();
        leyenda = new de.craften.ui.swingmaterial.MaterialButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cancelarButton = new de.craften.ui.swingmaterial.MaterialButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        gasolineraButton = new de.craften.ui.swingmaterial.MaterialButton();
        nivelButton = new de.craften.ui.swingmaterial.MaterialButton();
        plazasButton = new de.craften.ui.swingmaterial.MaterialButton();
        ind2 = new javax.swing.JLabel();
        ind1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        atras = new de.craften.ui.swingmaterial.MaterialButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Parking \"Villablanca\"");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 400, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pay.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(965, 35, -1, -1));

        finalizarButton.setText("          Ver factura y pagar");
        finalizarButton.setEnabled(false);
        finalizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarButtonActionPerformed(evt);
            }
        });
        jPanel2.add(finalizarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, 240, 70));

        jLabel46.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 50, 20));

        tiempo.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        tiempo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 28, 90, 20));

        jLabel47.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 190, 20));

        jLabel48.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 30, 40, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 100));

        plazas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setText("Seleccione la planta :");
        plazas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 180, 30));

        jLabel17.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel17.setText("(1 adaptados)");
        plazas.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, 80, 20));

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel18.setText("9");
        plazas.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 180, -1, -1));

        jLabel28.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel28.setText("978 m.");
        plazas.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, -1, -1));

        precio.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        precio.setText("0,59 €/hora");
        plazas.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, -1, -1));

        jLabel30.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel30.setText("12");
        plazas.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, -1, -1));

        jLabel31.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel31.setText("33");
        plazas.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, -1, -1));

        jLabel32.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel32.setText("6");
        plazas.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, -1, -1));

        jLabel33.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel33.setText("60");
        plazas.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, -1, -1));

        jLabel34.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel34.setText("NO");
        plazas.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, -1, -1));

        jLabel35.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel35.setText("2");
        plazas.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, -1, -1));

        direccion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        direccion.setText("C/ de la Raya, 3");
        plazas.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 100, -1));
        plazas.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 270, 10));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        plazas.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 20, 370));
        plazas.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 270, 10));

        planta0.setBackground(new java.awt.Color(102, 102, 102));
        planta0.setText("Planta 0");
        planta0.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        planta0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planta0ActionPerformed(evt);
            }
        });
        plazas.add(planta0, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 120, 60));

        planta1.setBackground(new java.awt.Color(204, 204, 204));
        planta1.setText("Planta 1");
        planta1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        planta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planta1ActionPerformed(evt);
            }
        });
        plazas.add(planta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 120, 60));

        planta2.setBackground(new java.awt.Color(204, 204, 204));
        planta2.setText("Planta 2");
        planta2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        planta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planta2ActionPerformed(evt);
            }
        });
        plazas.add(planta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 120, 60));

        p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMinus2.png"))); // NOI18N
        p1.setMnemonic(2);
        p1.setToolTipText("Libre");
        p1.setBorderPainted(false);
        p1.setContentAreaFilled(false);
        p1.setName("1"); // NOI18N
        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        plazas.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 146, 67, 83));

        p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ocupadoMinus2.png"))); // NOI18N
        p2.setMnemonic(2);
        p2.setToolTipText("Ocupado");
        p2.setBorderPainted(false);
        p2.setContentAreaFilled(false);
        p2.setName("2"); // NOI18N
        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        plazas.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 146, 67, 83));

        p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ocupadoMinus2.png"))); // NOI18N
        p3.setMnemonic(2);
        p3.setToolTipText("Ocupado");
        p3.setBorderPainted(false);
        p3.setContentAreaFilled(false);
        p3.setName("3"); // NOI18N
        p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        plazas.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 146, 67, 83));

        p4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche2.png"))); // NOI18N
        p4.setMnemonic(0);
        p4.setToolTipText("Libre");
        p4.setBorderPainted(false);
        p4.setContentAreaFilled(false);
        p4.setName("4"); // NOI18N
        p4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        plazas.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 146, 54, 83));

        p5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche2.png"))); // NOI18N
        p5.setMnemonic(0);
        p5.setToolTipText("Libre");
        p5.setBorderPainted(false);
        p5.setContentAreaFilled(false);
        p5.setName("5"); // NOI18N
        p5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        plazas.add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 146, 54, 83));

        p6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ocupadoCoche2.png"))); // NOI18N
        p6.setMnemonic(0);
        p6.setToolTipText("Ocupado");
        p6.setBorderPainted(false);
        p6.setContentAreaFilled(false);
        p6.setName("6"); // NOI18N
        p6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        plazas.add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 146, 54, 83));

        p7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ocupadoCoche2.png"))); // NOI18N
        p7.setMnemonic(0);
        p7.setToolTipText("Ocupado");
        p7.setBorderPainted(false);
        p7.setContentAreaFilled(false);
        p7.setName("7"); // NOI18N
        p7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        plazas.add(p7, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 146, 54, 83));

        p8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche2.png"))); // NOI18N
        p8.setMnemonic(0);
        p8.setToolTipText("Libre");
        p8.setBorderPainted(false);
        p8.setContentAreaFilled(false);
        p8.setName("8"); // NOI18N
        p8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        plazas.add(p8, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 146, 54, 83));

        p9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMotos2.png"))); // NOI18N
        p9.setMnemonic(1);
        p9.setToolTipText("Libre");
        p9.setBorderPainted(false);
        p9.setContentAreaFilled(false);
        p9.setName("9"); // NOI18N
        p9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        plazas.add(p9, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 145, 54, 44));

        p10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ocupadoMotos2.png"))); // NOI18N
        p10.setMnemonic(1);
        p10.setToolTipText("Ocupado");
        p10.setBorderPainted(false);
        p10.setContentAreaFilled(false);
        p10.setName("10"); // NOI18N
        p10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        plazas.add(p10, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 187, 54, 44));

        p11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMinus2.png"))); // NOI18N
        p11.setMnemonic(3);
        p11.setToolTipText("Libre");
        p11.setBorderPainted(false);
        p11.setContentAreaFilled(false);
        p11.setName("11"); // NOI18N
        p11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        plazas.add(p11, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 295, 67, 83));

        p12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMinus2.png"))); // NOI18N
        p12.setMnemonic(3);
        p12.setToolTipText("Libre");
        p12.setBorderPainted(false);
        p12.setContentAreaFilled(false);
        p12.setName("12"); // NOI18N
        p12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        plazas.add(p12, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 295, 67, 83));

        p13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche2.png"))); // NOI18N
        p13.setMnemonic(0);
        p13.setToolTipText("Libre");
        p13.setBorderPainted(false);
        p13.setContentAreaFilled(false);
        p13.setName("13"); // NOI18N
        p13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        plazas.add(p13, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 295, 54, 83));

        p14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ocupadoCoche2.png"))); // NOI18N
        p14.setMnemonic(0);
        p14.setToolTipText("Ocupado");
        p14.setBorderPainted(false);
        p14.setContentAreaFilled(false);
        p14.setName("14"); // NOI18N
        p14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        plazas.add(p14, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 295, 54, 83));

        p15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ocupadoCoche2.png"))); // NOI18N
        p15.setMnemonic(0);
        p15.setToolTipText("Ocupado");
        p15.setBorderPainted(false);
        p15.setContentAreaFilled(false);
        p15.setName("15"); // NOI18N
        p15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        plazas.add(p15, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 295, 54, 83));

        p16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche2.png"))); // NOI18N
        p16.setMnemonic(0);
        p16.setToolTipText("Libre");
        p16.setBorderPainted(false);
        p16.setContentAreaFilled(false);
        p16.setName("16"); // NOI18N
        p16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        plazas.add(p16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 295, 54, 83));

        p17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche2.png"))); // NOI18N
        p17.setMnemonic(0);
        p17.setToolTipText("Libre");
        p17.setBorderPainted(false);
        p17.setContentAreaFilled(false);
        p17.setName("17"); // NOI18N
        p17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        plazas.add(p17, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 295, 54, 83));

        p18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche2.png"))); // NOI18N
        p18.setMnemonic(0);
        p18.setToolTipText("Libre");
        p18.setBorderPainted(false);
        p18.setContentAreaFilled(false);
        p18.setName("18"); // NOI18N
        p18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        plazas.add(p18, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 295, 54, 83));

        p19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMotos2.png"))); // NOI18N
        p19.setMnemonic(1);
        p19.setToolTipText("Libre");
        p19.setBorderPainted(false);
        p19.setContentAreaFilled(false);
        p19.setName("19"); // NOI18N
        p19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        plazas.add(p19, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 294, 54, 44));

        p20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMotos2.png"))); // NOI18N
        p20.setMnemonic(1);
        p20.setToolTipText("Libre");
        p20.setBorderPainted(false);
        p20.setContentAreaFilled(false);
        p20.setName("20"); // NOI18N
        p20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });
        plazas.add(p20, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 336, 54, 44));

        parking.setForeground(new java.awt.Color(255, 255, 255));
        parking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ppequeño.png"))); // NOI18N
        parking.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        plazas.add(parking, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 140, 577, 240));

        reservarButton.setBackground(new java.awt.Color(0, 102, 0));
        reservarButton.setText("Reservar");
        reservarButton.setEnabled(false);
        reservarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservarButtonActionPerformed(evt);
            }
        });
        plazas.add(reservarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 140, 70));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/question.png"))); // NOI18N
        plazas.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 414, -1, -1));

        leyenda.setBackground(new java.awt.Color(204, 204, 204));
        leyenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/question.png"))); // NOI18N
        leyenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leyendaActionPerformed(evt);
            }
        });
        plazas.add(leyenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 80, 70));

        jLabel26.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("Localización");
        plazas.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 32, 120, -1));

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Precio");
        plazas.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 362, 120, -1));

        jLabel24.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Movilidad reducida");
        plazas.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 180, 120, -1));

        jLabel27.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("Distancia");
        plazas.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 72, 120, -1));

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Coches");
        plazas.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 150, 120, -1));

        jLabel21.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Baños");
        plazas.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 322, 120, -1));

        jLabel22.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Plazas totales");
        plazas.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 112, 120, -1));

        jLabel25.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Familiares");
        plazas.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 210, 120, -1));

        jLabel20.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Ascensor");
        plazas.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 282, 120, -1));

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Motos");
        plazas.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 240, 120, -1));

        cancelarButton.setBackground(new java.awt.Color(255, 51, 51));
        cancelarButton.setText("Cancelar reserva");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });
        plazas.add(cancelarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, 200, 70));

        getContentPane().add(plazas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 960, 490));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/gasolinera (1).png"))); // NOI18N
        jLabel3.setText(" Gasolinera");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/plaza.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/presion (1).png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 220, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/aceite (1) (1).png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 245, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel7.setText("Nivel de aire");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel8.setText("y aceite");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel10.setText("Reserva");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel11.setText("de plazas");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 65, -1, -1));

        gasolineraButton.setBackground(new java.awt.Color(0, 160, 160));
        gasolineraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gasolineraButtonActionPerformed(evt);
            }
        });
        jPanel1.add(gasolineraButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, 100));

        nivelButton.setBackground(new java.awt.Color(0, 160, 160));
        nivelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(nivelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 220, 110));

        plazasButton.setBackground(new java.awt.Color(0, 160, 160));
        plazasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plazasButtonActionPerformed(evt);
            }
        });
        jPanel1.add(plazasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 220, 100));

        ind2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/indicador.png"))); // NOI18N
        jPanel1.add(ind2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 10, -1));

        ind1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/indicador.png"))); // NOI18N
        jPanel1.add(ind1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/left-arrow.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 439, -1, -1));

        jLabel29.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel29.setText("ATRÁS");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 447, -1, -1));

        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        jPanel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 150, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 92, 220, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gasolineraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gasolineraButtonActionPerformed
        if (aux != gas) {
            getContentPane().remove(aux);
            aux = gas;
            getContentPane().add(aux, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 960, 490));
            jPanel1.remove(ind1);
            jPanel1.add(ind1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));
            jPanel1.remove(ind2);
            jPanel1.add(ind2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 10, -1));
            revalidate();
            repaint();
            pack();
        }
    }//GEN-LAST:event_gasolineraButtonActionPerformed

    private void nivelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelButtonActionPerformed
        if (aux != niv) {
            getContentPane().remove(aux);
            aux = niv;
            getContentPane().add(aux, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 960, 490));
            jPanel1.remove(ind1);
            jPanel1.add(ind1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 225, -1, -1));
            jPanel1.remove(ind2);
            jPanel1.add(ind2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 225, 10, -1));
            revalidate();
            repaint();
            pack();
        }
    }//GEN-LAST:event_nivelButtonActionPerformed

    private void planta0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planta0ActionPerformed
        planta0.setBackground(new java.awt.Color(102, 102, 102));
        planta0.setFont(new java.awt.Font("Roboto Medium", 1, 14));
        planta1.setBackground(new java.awt.Color(204, 204, 204));
        planta1.setFont(new java.awt.Font("Roboto", 0, 14));
        planta2.setBackground(new java.awt.Color(204, 204, 204));
        planta2.setFont(new java.awt.Font("Roboto", 0, 14));
        libre(p1);
        ocupado(p2);
        ocupado(p3);
        libre(p4);
        libre(p5);
        ocupado(p6);
        ocupado(p7);
        libre(p8);
        libre(p9);
        ocupado(p10);
        libre(p11);
        libre(p12);
        libre(p13);
        ocupado(p14);
        ocupado(p15);
        libre(p16);
        libre(p17);
        libre(p18);
        libre(p19);
        libre(p20);
        planta = "0";
    }//GEN-LAST:event_planta0ActionPerformed

    private void planta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planta1ActionPerformed
        planta1.setBackground(new java.awt.Color(102, 102, 102));
        planta1.setFont(new java.awt.Font("Roboto Medium", 1, 14));
        planta0.setBackground(new java.awt.Color(204, 204, 204));
        planta0.setFont(new java.awt.Font("Roboto", 0, 14));
        planta2.setBackground(new java.awt.Color(204, 204, 204));
        planta2.setFont(new java.awt.Font("Roboto", 0, 14));
        libre(p1);
        ocupado(p2);
        ocupado(p3);
        ocupado(p4);
        ocupado(p5);
        ocupado(p6);
        libre(p7);
        libre(p8);
        libre(p9);
        libre(p10);
        libre(p11);
        ocupado(p12);
        libre(p13);
        ocupado(p14);
        libre(p15);
        libre(p16);
        ocupado(p17);
        ocupado(p18);
        ocupado(p19);
        ocupado(p20);
        planta = "1";
    }//GEN-LAST:event_planta1ActionPerformed

    private void planta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planta2ActionPerformed
        planta2.setBackground(new java.awt.Color(102, 102, 102));
        planta2.setFont(new java.awt.Font("Roboto Medium", 1, 14));
        planta1.setBackground(new java.awt.Color(204, 204, 204));
        planta1.setFont(new java.awt.Font("Roboto", 0, 14));
        planta0.setBackground(new java.awt.Color(204, 204, 204));
        planta0.setFont(new java.awt.Font("Roboto", 0, 14));
        libre(p1);
        libre(p2);
        libre(p3);
        libre(p4);
        ocupado(p5);
        libre(p6);
        libre(p7);
        libre(p8);
        libre(p9);
        libre(p10);
        libre(p11);
        ocupado(p12);
        ocupado(p13);
        libre(p14);
        libre(p15);
        libre(p16);
        libre(p17);
        ocupado(p18);
        libre(p19);
        libre(p20);
        planta = "2";
    }//GEN-LAST:event_planta2ActionPerformed

    private void accion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accion
        javax.swing.JButton aux = (javax.swing.JButton) evt.getSource();
        if (!aux.getToolTipText().equals("Ocupado")) {
            int i = Integer.parseInt(aux.getName());
            if (lib[i - 1]) {
                if (sel != null) {
                    libre(sel);
                    lib[Integer.parseInt(sel.getName()) - 1] = true;
                }
                reservado(aux);
                lib[i - 1] = false;
                sel = aux;
                reservarButton.setEnabled(true);
            } else {
                libre(aux);
                lib[i - 1] = true;
                sel = null;
                reservarButton.setEnabled(false);
            }
        }
    }//GEN-LAST:event_accion

    private void plazasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plazasButtonActionPerformed
        if (aux != plazas) {
            getContentPane().remove(aux);
            aux = plazas;
            getContentPane().add(aux, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 960, 490));
            jPanel1.remove(ind1);
            jPanel1.add(ind1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));
            jPanel1.remove(ind2);
            jPanel1.add(ind2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 10, -1));
            revalidate();
            repaint();
            pack();
        }
    }//GEN-LAST:event_plazasButtonActionPerformed

    private void reservarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservarButtonActionPerformed
        Reserva rev = new Reserva(this, true, sel, planta, direccion.getText(), precio.getText(), "Villablanca");
        rev.setLocationRelativeTo(null);
        getRootPane().getGlassPane().setVisible(true);
        rev.setVisible(true);
        getRootPane().getGlassPane().setVisible(false);
        if (Reserva.getSi()) {
            finalizarButton.setEnabled(true);
            hora = 0;
            min = 01;
            seg = 01;
            plazas.remove(reservarButton);
            activarBotones(false);
            sel.setEnabled(true);
            plazas.add(cancelarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, 200, 70));
            revalidate();
            repaint();
            pack();
            jLabel46.setText("Queda");
            jLabel47.setText("que estacione su vehículo");
            jLabel48.setText("para");
            timer = new Timer();
            task = new TimerTask() {
                @Override
                public void run() {
                    corriendo = true;
                    if (seg > 0) {
                        seg--;
                    } else {
                        seg = 59;
                        if (min > 0) {
                            min--;
                        } else {
                            min = 59;
                            if (hora > 0) {
                                hora--;
                            } // si segundo = 0, minuto = 0 y hora = 0,
                            // cancelamos el timer
                            else {
                                corriendo = false;
                                timer.cancel();
                                tiempo.setText("");
                                jLabel46.setText("");
                                jLabel47.setText("");
                                jLabel48.setText("");
                                reservarButton.setEnabled(false);
                                confirmacion3();
                                activarBotones(true);
                                Reserva.reset();
                                libre(sel);
                                sel=null;
                                plazas.remove(cancelarButton);
                                plazas.add(reservarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 140, 70));
                                repaint();
                                revalidate();
                                pack();
                                if (Gasolinera.gasDate == null && Lavadero.lavDate == null) {
                                    finalizarButton.setEnabled(false);
                                }
                                hora = 0;
                                min = 01;
                                seg = 01;
                            }
                        }
                    }
                    if (corriendo) {
                        tiempo.setText(String.format("%02d", hora) + ":" + String.format("%02d", min) + ":" + String.format("%02d", seg));
                    }
                }
            };
            timer.schedule(task, 0, 1000);
        }
    }//GEN-LAST:event_reservarButtonActionPerformed

    public void confirmacion3() {
        Confirmacion3 conf = new Confirmacion3(this, true);
        activarSombra(conf);
    }

    private void finalizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarButtonActionPerformed
        Ticket tik = new Ticket(this, true, 0.59);
        tik.setLocationRelativeTo(null);
        getRootPane().getGlassPane().setVisible(true);
        tik.setVisible(true);
        getRootPane().getGlassPane().setVisible(false);
    }//GEN-LAST:event_finalizarButtonActionPerformed

    private void leyendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leyendaActionPerformed
        Leyenda ley = new Leyenda(this, true);
        ley.setLocationRelativeTo(null);
        getRootPane().getGlassPane().setVisible(true);
        ley.setVisible(true);
        getRootPane().getGlassPane().setVisible(false);
    }//GEN-LAST:event_leyendaActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        corriendo = false;
        timer.cancel();
        tiempo.setText("");
        jLabel46.setText("");
        jLabel47.setText("");
        jLabel48.setText("");
        reservarButton.setEnabled(false);
        activarBotones(true);
        Reserva.reset();
        libre(sel);
        sel=null;
        plazas.add(reservarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 140, 70));
        repaint();
        revalidate();
        pack();
        if (Gasolinera.gasDate == null && Lavadero.lavDate == null) {
            finalizarButton.setEnabled(false);
        }
        hora = 0;
        min = 01;
        seg = 01;
        plazas.remove(cancelarButton);
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        Confirmacion2 conf = new Confirmacion2(this, true);
        conf.setLocationRelativeTo(null);
        getRootPane().getGlassPane().setVisible(true);
        conf.setVisible(true);
        getRootPane().getGlassPane().setVisible(false);
    }//GEN-LAST:event_atrasActionPerformed

    private void libre(javax.swing.JButton but) {
        switch (but.getMnemonic()) {
            case 0:
                but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreCoche2.png")));
                break;
            case 1:
                but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMotos2.png")));
                break;
            case 2:
                but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMinus2.png")));
                break;
            case 3:
                but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/libreMinus2.png")));
                break;
        }
        but.setToolTipText("Libre");
    }

    private void ocupado(javax.swing.JButton but) {
        switch (but.getMnemonic()) {
            case 0:
                but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ocupadoCoche2.png")));
                break;
            case 1:
                but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ocupadoMotos2.png")));
                break;
            case 2:
                but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ocupadoMinus2.png")));
                break;
            case 3:
                but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ocupadoMinus2.png")));
                break;
        }
        but.setToolTipText("Ocupado");
    }

    private void reservado(javax.swing.JButton but) {
        switch (but.getMnemonic()) {
            case 0:
                but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/reservadoCoche2.png")));
                break;
            case 1:
                but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/reservadoMotos2.png")));
                break;
            case 2:
                but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/reservadoMinus2.png")));
                break;
            case 3:
                but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/reservadoMinus2.png")));
                break;
        }
        but.setToolTipText("Reservado");
    }

    public void activarBotones(boolean i) {
        p1.setEnabled(i);
        p2.setEnabled(i);
        p3.setEnabled(i);
        p4.setEnabled(i);
        p5.setEnabled(i);
        p6.setEnabled(i);
        p7.setEnabled(i);
        p8.setEnabled(i);
        p9.setEnabled(i);
        p10.setEnabled(i);
        p11.setEnabled(i);
        p12.setEnabled(i);
        p13.setEnabled(i);
        p14.setEnabled(i);
        p15.setEnabled(i);
        p16.setEnabled(i);
        p17.setEnabled(i);
        p18.setEnabled(i);
        p19.setEnabled(i);
        p20.setEnabled(i);
        planta0.setEnabled(i);
        planta1.setEnabled(i);
        planta2.setEnabled(i);
    }

    private String planta;
    private boolean[] lib;
    private javax.swing.JButton sel;
    private de.craften.ui.swingmaterial.MaterialPanel aux, gas, niv;
    private boolean corriendo;
    private int hora, min, seg;
    private Timer timer;
    private TimerTask task;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.craften.ui.swingmaterial.MaterialButton atras;
    private de.craften.ui.swingmaterial.MaterialButton cancelarButton;
    private static javax.swing.JLabel direccion;
    public static de.craften.ui.swingmaterial.MaterialButton finalizarButton;
    private de.craften.ui.swingmaterial.MaterialButton gasolineraButton;
    private javax.swing.JLabel ind1;
    private javax.swing.JLabel ind2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private static javax.swing.JLabel jLabel46;
    private static javax.swing.JLabel jLabel47;
    private static javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private de.craften.ui.swingmaterial.MaterialButton leyenda;
    private de.craften.ui.swingmaterial.MaterialButton nivelButton;
    private javax.swing.JButton p1;
    private javax.swing.JButton p10;
    private javax.swing.JButton p11;
    private javax.swing.JButton p12;
    private javax.swing.JButton p13;
    private javax.swing.JButton p14;
    private javax.swing.JButton p15;
    private javax.swing.JButton p16;
    private javax.swing.JButton p17;
    private javax.swing.JButton p18;
    private javax.swing.JButton p19;
    private javax.swing.JButton p2;
    private javax.swing.JButton p20;
    private javax.swing.JButton p3;
    private javax.swing.JButton p4;
    private javax.swing.JButton p5;
    private javax.swing.JButton p6;
    private javax.swing.JButton p7;
    private javax.swing.JButton p8;
    private javax.swing.JButton p9;
    private javax.swing.JLabel parking;
    private de.craften.ui.swingmaterial.MaterialButton planta0;
    private de.craften.ui.swingmaterial.MaterialButton planta1;
    private de.craften.ui.swingmaterial.MaterialButton planta2;
    private de.craften.ui.swingmaterial.MaterialPanel plazas;
    private de.craften.ui.swingmaterial.MaterialButton plazasButton;
    private static javax.swing.JLabel precio;
    private de.craften.ui.swingmaterial.MaterialButton reservarButton;
    private static javax.swing.JLabel tiempo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void activarBoton(boolean p) {
        finalizarButton.setEnabled(p);
    }

    @Override
    public void activarSombra(JDialog j) {
        j.setLocationRelativeTo(null);
        getRootPane().getGlassPane().setVisible(true);
        j.setVisible(true);
        getRootPane().getGlassPane().setVisible(false);
    }
    
    @Override
    public void parar() {
        timer.cancel();
    }
}
