/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aparcamiento.servicios;

import java.awt.Color;

/**
 *
 * @author jorge
 */
public class CombustibleVilla extends javax.swing.JDialog {

    /**
     * Creates new form CombustibleVilla
     */
    public CombustibleVilla(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        materialButton1 = new de.craften.ui.swingmaterial.MaterialButton();
        materialButton2 = new de.craften.ui.swingmaterial.MaterialButton();
        materialButton3 = new de.craften.ui.swingmaterial.MaterialButton();
        materialButton4 = new de.craften.ui.swingmaterial.MaterialButton();
        materialTextField1 = new de.craften.ui.swingmaterial.MaterialTextField();
        materialButton5 = new de.craften.ui.swingmaterial.MaterialButton();
        materialButton6 = new de.craften.ui.swingmaterial.MaterialButton();
        materialButton7 = new de.craften.ui.swingmaterial.MaterialButton();
        materialButton8 = new de.craften.ui.swingmaterial.MaterialButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setText("Tipo de combustible:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 165, 32));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("Cantidad:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 90, 24));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setText("Precio de la gasolina");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 113, 17));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setText("seleccionada:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 74, 17));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/600px-WV-95.svg.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/240px-WV-98.svg.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/combustible.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/diesel.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/euro.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/drop.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        materialButton1.setBackground(new java.awt.Color(0, 204, 204));
        materialButton1.setText("          Gasolina 95");
        materialButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(materialButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 190, 70));

        materialButton2.setBackground(new java.awt.Color(0, 204, 204));
        materialButton2.setText("          Diésel normal");
        materialButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(materialButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 190, 70));

        materialButton3.setBackground(new java.awt.Color(0, 204, 204));
        materialButton3.setText("          Gasolina 98");
        materialButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(materialButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 190, 70));

        materialButton4.setBackground(new java.awt.Color(0, 204, 204));
        materialButton4.setText("          Diésel Efitec");
        materialButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(materialButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 190, 70));

        materialTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                materialTextField1KeyTyped(evt);
            }
        });
        jPanel2.add(materialTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 30, 70));

        materialButton5.setBackground(new java.awt.Color(255, 204, 0));
        materialButton5.setText("          LITROS");
        materialButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(materialButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 140, 70));

        materialButton6.setBackground(new java.awt.Color(255, 204, 0));
        materialButton6.setText("          EUROS");
        materialButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(materialButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 140, 70));

        materialButton7.setBackground(new java.awt.Color(0, 102, 0));
        materialButton7.setText("ACEPTAR");
        jPanel2.add(materialButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 140, 70));

        materialButton8.setBackground(new java.awt.Color(255, 51, 51));
        materialButton8.setText("CANCELAR");
        jPanel2.add(materialButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 140, 70));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void materialButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButton5ActionPerformed
        materialButton5.setBackground(new java.awt.Color(204,153,0));        // TODO add your handling code here:
        materialButton5.setFont(new java.awt.Font("Roboto Medium", 1, 15));
        materialButton6.setBackground(new java.awt.Color(255, 204,0));        // TODO add your handling code here:
        materialButton6.setFont(new java.awt.Font("Roboto Medium", 0, 14));
        materialButton5.setForeground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_materialButton5ActionPerformed

    private void materialButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButton6ActionPerformed
        materialButton6.setBackground(new java.awt.Color(204,153,0));        // TODO add your handling code here:
        materialButton6.setFont(new java.awt.Font("Roboto Medium", 1, 15));
        materialButton5.setBackground(new java.awt.Color(255, 204,0));        // TODO add your handling code here:
        materialButton5.setFont(new java.awt.Font("Roboto Medium", 0, 14));
        materialButton6.setForeground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_materialButton6ActionPerformed

    private void materialButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButton1ActionPerformed
        materialButton2.setBackground(new java.awt.Color(0, 204, 204));        // TODO add your handling code here:
        materialButton2.setFont(new java.awt.Font("Roboto Medium", 0, 14));
        materialButton4.setBackground(new java.awt.Color(0, 204, 204));        // TODO add your handling code here:
        materialButton4.setFont(new java.awt.Font("Roboto Medium", 0, 14));
        materialButton1.setBackground(new java.awt.Color(0, 153, 153));        // TODO add your handling code here:
        materialButton1.setFont(new java.awt.Font("Roboto Medium", 1, 14));
        materialButton3.setBackground(new java.awt.Color(0, 204, 204));        // TODO add your handling code here:
        materialButton3.setFont(new java.awt.Font("Roboto Medium", 0, 14));        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_materialButton1ActionPerformed

    private void materialButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButton3ActionPerformed
        materialButton1.setBackground(new java.awt.Color(0, 204, 204));        // TODO add your handling code here:
        materialButton1.setFont(new java.awt.Font("Roboto Medium", 0, 14));
        materialButton4.setBackground(new java.awt.Color(0, 204, 204));        // TODO add your handling code here:
        materialButton4.setFont(new java.awt.Font("Roboto Medium", 0, 14));
        materialButton3.setBackground(new java.awt.Color(0, 153, 153));        // TODO add your handling code here:
        materialButton3.setFont(new java.awt.Font("Roboto Medium", 1, 14));
        materialButton2.setBackground(new java.awt.Color(0, 204, 204));        // TODO add your handling code here:
        materialButton2.setFont(new java.awt.Font("Roboto Medium", 0, 14));        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_materialButton3ActionPerformed

    private void materialButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButton2ActionPerformed
        materialButton1.setBackground(new java.awt.Color(0, 204, 204));        // TODO add your handling code here:
        materialButton1.setFont(new java.awt.Font("Roboto Medium", 0, 14));
        materialButton4.setBackground(new java.awt.Color(0, 204, 204));        // TODO add your handling code here:
        materialButton4.setFont(new java.awt.Font("Roboto Medium", 0, 14));
        materialButton2.setBackground(new java.awt.Color(0, 153, 153));        // TODO add your handling code here:
        materialButton2.setFont(new java.awt.Font("Roboto Medium", 1, 14));
        materialButton3.setBackground(new java.awt.Color(0, 204, 204));        // TODO add your handling code here:
        materialButton3.setFont(new java.awt.Font("Roboto Medium", 0, 14));        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_materialButton2ActionPerformed

    private void materialButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButton4ActionPerformed
        materialButton1.setBackground(new java.awt.Color(0, 204, 204));        // TODO add your handling code here:
        materialButton1.setFont(new java.awt.Font("Roboto Medium", 0, 14));
        materialButton2.setBackground(new java.awt.Color(0, 204, 204));        // TODO add your handling code here:
        materialButton2.setFont(new java.awt.Font("Roboto Medium", 0, 14));
        materialButton4.setBackground(new java.awt.Color(0, 153, 153));        // TODO add your handling code here:
        materialButton4.setFont(new java.awt.Font("Roboto Medium", 1, 14));
        materialButton3.setBackground(new java.awt.Color(0, 204, 204));        // TODO add your handling code here:
        materialButton3.setFont(new java.awt.Font("Roboto Medium", 0, 14));        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_materialButton4ActionPerformed

    private void materialTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_materialTextField1KeyTyped
        if(materialTextField1.getText().length()>=2){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_materialTextField1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CombustibleVilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CombustibleVilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CombustibleVilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CombustibleVilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CombustibleVilla dialog = new CombustibleVilla(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private de.craften.ui.swingmaterial.MaterialButton materialButton1;
    private de.craften.ui.swingmaterial.MaterialButton materialButton2;
    private de.craften.ui.swingmaterial.MaterialButton materialButton3;
    private de.craften.ui.swingmaterial.MaterialButton materialButton4;
    private de.craften.ui.swingmaterial.MaterialButton materialButton5;
    private de.craften.ui.swingmaterial.MaterialButton materialButton6;
    private de.craften.ui.swingmaterial.MaterialButton materialButton7;
    private de.craften.ui.swingmaterial.MaterialButton materialButton8;
    private de.craften.ui.swingmaterial.MaterialTextField materialTextField1;
    // End of variables declaration//GEN-END:variables
}
