/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aparcamiento.servicios;

import java.awt.Color;

/**
 *
 * @author jorge
 */
public class Combustible extends javax.swing.JDialog {

    /**
     * Creates new form Co
     */
    public Combustible(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        litrosButton = new de.craften.ui.swingmaterial.MaterialButton();
        eurosButton = new de.craften.ui.swingmaterial.MaterialButton();
        cantidad = new de.craften.ui.swingmaterial.MaterialTextField();
        jLabel5 = new javax.swing.JLabel();
        gasolina95button = new de.craften.ui.swingmaterial.MaterialButton();
        jLabel7 = new javax.swing.JLabel();
        gasolina98button = new de.craften.ui.swingmaterial.MaterialButton();
        jLabel6 = new javax.swing.JLabel();
        dieselButton = new de.craften.ui.swingmaterial.MaterialButton();
        jLabel8 = new javax.swing.JLabel();
        efitecButton = new de.craften.ui.swingmaterial.MaterialButton();
        aceptarButton = new de.craften.ui.swingmaterial.MaterialButton();
        CancelarButton = new de.craften.ui.swingmaterial.MaterialButton();
        precio = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        precio1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        euros = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setPreferredSize(new java.awt.Dimension(506, 300));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setText("1. Elija el tipo de combustible:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 32));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("3. Seleccione el modo:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 200, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/drop.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/euro.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 30, -1));

        litrosButton.setBackground(new java.awt.Color(255, 204, 0));
        litrosButton.setBorder(null);
        litrosButton.setText("          LITROS");
        litrosButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        litrosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                litrosButtonActionPerformed(evt);
            }
        });
        jPanel2.add(litrosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 140, 70));

        eurosButton.setBackground(new java.awt.Color(255, 204, 0));
        eurosButton.setText("          EUROS");
        eurosButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        eurosButton.setName(""); // NOI18N
        eurosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eurosButtonActionPerformed(evt);
            }
        });
        jPanel2.add(eurosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 140, 70));

        cantidad.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });
        cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadKeyTyped(evt);
            }
        });
        jPanel2.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 30, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/600px-WV-95.svg.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        gasolina95button.setBackground(new java.awt.Color(0, 204, 204));
        gasolina95button.setBorder(null);
        gasolina95button.setText("          Gasolina 95");
        gasolina95button.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        gasolina95button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gasolina95buttonActionPerformed(evt);
            }
        });
        jPanel2.add(gasolina95button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 200, 70));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/240px-WV-98.svg.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        gasolina98button.setBackground(new java.awt.Color(0, 204, 204));
        gasolina98button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/240px-WV-98.svg.png"))); // NOI18N
        gasolina98button.setText("          Gasolina 98");
        gasolina98button.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        gasolina98button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gasolina98buttonActionPerformed(evt);
            }
        });
        jPanel2.add(gasolina98button, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 200, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/combustible.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        dieselButton.setBackground(new java.awt.Color(0, 204, 204));
        dieselButton.setText("          Diésel normal");
        dieselButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        dieselButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dieselButtonActionPerformed(evt);
            }
        });
        jPanel2.add(dieselButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 200, 70));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/diesel.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 30, -1));

        efitecButton.setBackground(new java.awt.Color(0, 204, 204));
        efitecButton.setText("          Diésel Efitec");
        efitecButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        efitecButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efitecButtonActionPerformed(evt);
            }
        });
        jPanel2.add(efitecButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 200, 70));

        aceptarButton.setBackground(new java.awt.Color(0, 102, 0));
        aceptarButton.setText("Aceptar");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });
        jPanel2.add(aceptarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 140, 70));

        CancelarButton.setBackground(new java.awt.Color(255, 51, 51));
        CancelarButton.setText("Cancelar");
        CancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarButtonActionPerformed(evt);
            }
        });
        jPanel2.add(CancelarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 140, 70));

        precio.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        precio.setText("-");
        jPanel2.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 50, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel11.setText("seleccionada:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        precio1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        precio1.setText("€/litro");
        jPanel2.add(precio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel12.setText("Precio de la gasolina");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel14.setText("El total a pagar es:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 120, -1));

        euros.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        euros.setText("0,00 € (0,00 litros)");
        jPanel2.add(euros, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 170, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel9.setText("2. Introduzca la cantidad:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 200, -1));

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadActionPerformed

    private void litrosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_litrosButtonActionPerformed
        litrosButton.setBackground(new java.awt.Color(204, 153, 0));        // TODO add your handling code here:
        litrosButton.setFont(new java.awt.Font("Roboto Medium", 1, 14));
        eurosButton.setBackground(new java.awt.Color(255, 204, 0));        // TODO add your handling code here:
        eurosButton.setFont(new java.awt.Font("Roboto", 0, 14));
        litrosButton.setForeground(Color.WHITE);
        totalCombustible = String.format("%.2f", Double.parseDouble(cantidad.getText()) * price) + " €";
        euros.setText(totalCombustible + " (" + String.format("%.2f", Double.parseDouble(cantidad.getText())) + " litros)");
    }//GEN-LAST:event_litrosButtonActionPerformed

    private void gasolina95buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gasolina95buttonActionPerformed
        gasolina98button.setBackground(new java.awt.Color(0, 204, 204));        // TODO add your handling code here:
        gasolina98button.setFont(new java.awt.Font("Roboto", 0, 14));
        dieselButton.setBackground(new java.awt.Color(0, 204, 204));        // TODO add your handling code here:
        dieselButton.setFont(new java.awt.Font("Roboto", 0, 14));
        gasolina95button.setBackground(new java.awt.Color(0, 153, 153));        // TODO add your handling code here:
        gasolina95button.setFont(new java.awt.Font("Roboto Medium", 1, 14));
        efitecButton.setBackground(new java.awt.Color(0, 204, 204));        // TODO add your handling code here:
        efitecButton.setFont(new java.awt.Font("Roboto", 0, 14));
        price = 1.232;
        precio.setText("1,232");
    }//GEN-LAST:event_gasolina95buttonActionPerformed

    private void gasolina98buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gasolina98buttonActionPerformed
        gasolina95button.setBackground(new java.awt.Color(0, 204, 204));        // TODO add your handling code here:
        gasolina95button.setFont(new java.awt.Font("Roboto", 0, 14));
        dieselButton.setBackground(new java.awt.Color(0, 204, 204));        // TODO add your handling code here:
        dieselButton.setFont(new java.awt.Font("Roboto", 0, 14));
        gasolina98button.setBackground(new java.awt.Color(0, 153, 153));        // TODO add your handling code here:
        gasolina98button.setFont(new java.awt.Font("Roboto Medium", 1, 14));
        efitecButton.setBackground(new java.awt.Color(0, 204, 204));        // TODO add your handling code here:
        efitecButton.setFont(new java.awt.Font("Roboto", 0, 14));
        price = 1.317;
        precio.setText("1,317");

    }//GEN-LAST:event_gasolina98buttonActionPerformed

    private void dieselButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dieselButtonActionPerformed
        gasolina95button.setBackground(new java.awt.Color(0, 204, 204));        // TODO add your handling code here:
        gasolina95button.setFont(new java.awt.Font("Roboto", 0, 14));
        gasolina98button.setBackground(new java.awt.Color(0, 204, 204));        // TODO add your handling code here:
        gasolina98button.setFont(new java.awt.Font("Roboto", 0, 14));
        dieselButton.setBackground(new java.awt.Color(0, 153, 153));        // TODO add your handling code here:
        dieselButton.setFont(new java.awt.Font("Roboto Medium", 1, 14));
        efitecButton.setBackground(new java.awt.Color(0, 204, 204));        // TODO add your handling code here:
        efitecButton.setFont(new java.awt.Font("Roboto", 0, 14));
        price = 1.023;
        precio.setText("1,023");
    }//GEN-LAST:event_dieselButtonActionPerformed

    private void efitecButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efitecButtonActionPerformed
        gasolina95button.setBackground(new java.awt.Color(0, 204, 204));        // TODO add your handling code here:
        gasolina95button.setFont(new java.awt.Font("Roboto", 0, 14));
        dieselButton.setBackground(new java.awt.Color(0, 204, 204));        // TODO add your handling code here:
        dieselButton.setFont(new java.awt.Font("Roboto", 0, 14));
        efitecButton.setBackground(new java.awt.Color(0, 153, 153));        // TODO add your handling code here:
        efitecButton.setFont(new java.awt.Font("Roboto Medium", 1, 14));
        gasolina98button.setBackground(new java.awt.Color(0, 204, 204));        // TODO add your handling code here:
        gasolina98button.setFont(new java.awt.Font("Roboto", 0, 14));
        price = 1.115;
        precio.setText("1,115");
    }//GEN-LAST:event_efitecButtonActionPerformed

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarButtonActionPerformed

    private void CancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarButtonActionPerformed
        this.setVisible(false);        // TODO add your handling code here:
        totalCombustible=null;
    }//GEN-LAST:event_CancelarButtonActionPerformed

    private void eurosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eurosButtonActionPerformed
        eurosButton.setBackground(new java.awt.Color(204, 153, 0));        // TODO add your handling code here:
        eurosButton.setFont(new java.awt.Font("Roboto Medium", 1, 14));
        litrosButton.setBackground(new java.awt.Color(255, 204, 0));        // TODO add your handling code here:
        litrosButton.setFont(new java.awt.Font("Roboto", 0, 14));
        eurosButton.setForeground(Color.WHITE);
        totalCombustible = String.format("%.2f", Double.parseDouble(cantidad.getText())) + " €";
        euros.setText(totalCombustible + " (" + String.format("%.2f", Double.parseDouble(cantidad.getText()) / price) + " litros)");
    }//GEN-LAST:event_eurosButtonActionPerformed
    
    private void cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyTyped
        if(cantidad.getText().length() >= 2) evt.consume();
    }//GEN-LAST:event_cantidadKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Combustible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Combustible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Combustible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Combustible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Combustible dialog = new Combustible(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private static String totalCombustible;
    private double price;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.craften.ui.swingmaterial.MaterialButton CancelarButton;
    private de.craften.ui.swingmaterial.MaterialButton aceptarButton;
    private de.craften.ui.swingmaterial.MaterialTextField cantidad;
    private de.craften.ui.swingmaterial.MaterialButton dieselButton;
    private de.craften.ui.swingmaterial.MaterialButton efitecButton;
    private javax.swing.JLabel euros;
    private de.craften.ui.swingmaterial.MaterialButton eurosButton;
    private de.craften.ui.swingmaterial.MaterialButton gasolina95button;
    private de.craften.ui.swingmaterial.MaterialButton gasolina98button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private de.craften.ui.swingmaterial.MaterialButton litrosButton;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel precio1;
    // End of variables declaration//GEN-END:variables
}
