/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aparcamiento.servicios;

import java.awt.Color;
import java.awt.event.MouseEvent;

/**
 *
 * @author david
 */
public class Nivel extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Nivel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        materialPanel1 = new de.craften.ui.swingmaterial.MaterialPanel();
        euros = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        aceiteButton = new de.craften.ui.swingmaterial.MaterialButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ruedasButton = new de.craften.ui.swingmaterial.MaterialButton();
        bar = new de.craften.ui.swingmaterial.MaterialTextField();
        jLabel5 = new javax.swing.JLabel();
        kms = new de.craften.ui.swingmaterial.MaterialTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cambioAceite = new javax.swing.JLabel();
        hinchaRuedas = new javax.swing.JLabel();
        materialButton1 = new de.craften.ui.swingmaterial.MaterialButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        materialPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        euros.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        euros.setText(" Servicio gratuito");
        euros.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        materialPanel1.add(euros, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 190, 50));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel10.setText(" Medidor de aceite y aire");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        materialPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 275, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/presion (1).png"))); // NOI18N
        materialPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/aceite (1) (1).png"))); // NOI18N
        materialPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setText("Si desea usar alguna de las siguientes funciones, introduzca los campos de texto indicados y presione \"Analizar\":");
        materialPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 710, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/oil.png"))); // NOI18N
        materialPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 158, -1, -1));

        aceiteButton.setBackground(new java.awt.Color(0, 204, 204));
        aceiteButton.setBorder(null);
        aceiteButton.setText("         cambio de aceite");
        aceiteButton.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        materialPanel1.add(aceiteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 240, 70));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel7.setText("marcado por el odómetro:");
        materialPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 190, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        materialPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 20, 140));

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel12.setText("Número de kilómetros");
        materialPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 190, -1));

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel14.setText("marcado por el manómetro:");
        materialPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 200, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel9.setText("Número de bares");
        materialPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 150, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/car.png"))); // NOI18N
        materialPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 158, 30, -1));

        ruedasButton.setBackground(new java.awt.Color(0, 204, 204));
        ruedasButton.setBorder(null);
        ruedasButton.setText("         hinchado de neúmaticos");
        ruedasButton.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        materialPanel1.add(ruedasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 310, 70));

        bar.setAccent(new java.awt.Color(0, 204, 204));
        bar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        bar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                barKeyTyped(evt);
            }
        });
        materialPanel1.add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 40, 60));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setText("bares");
        materialPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 260, 50, -1));

        kms.setAccent(new java.awt.Color(0, 204, 204));
        kms.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        kms.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kmsKeyTyped(evt);
            }
        });
        materialPanel1.add(kms, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 70, 60));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel11.setText("kms.");
        materialPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 50, -1));

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel16.setText("Resultado:");
        materialPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 100, -1));

        cambioAceite.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cambioAceite.setText("      ____");
        materialPanel1.add(cambioAceite, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 375, 310, 30));

        hinchaRuedas.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        materialPanel1.add(hinchaRuedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 310, 30));

        materialButton1.setBackground(new java.awt.Color(204, 0, 102));
        materialButton1.setText("Analizar");
        materialButton1.setFont(new java.awt.Font("Roboto Medium", 1, 16)); // NOI18N
        materialButton1.setSelected(true);
        materialButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButton1ActionPerformed(evt);
            }
        });
        materialPanel1.add(materialButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 150, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(materialPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(materialPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barKeyTyped
        if (bar.getText().length() >= 3) {
            evt.consume();
        }
    }//GEN-LAST:event_barKeyTyped

    private void kmsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kmsKeyTyped
        if (kms.getText().length() >= 6) {
            evt.consume();
        }
    }//GEN-LAST:event_kmsKeyTyped

    private void materialButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButton1ActionPerformed
        if (!bar.getText().equals("")) {
            cambioAceite.setText("");
            if (Double.parseDouble(bar.getText()) > 2.1d || Double.parseDouble(bar.getText()) < 1.8d) {
                hinchaRuedas.setText("- Es preciso hinchar los neumáticos");
            } else {
                hinchaRuedas.setText("- No es preciso hinchar los neumáticos");
            }
        } else {
            hinchaRuedas.setText("");
        }

        if (!kms.getText().equals("")) {
            if (Double.parseDouble(kms.getText()) > 5000) {
                cambioAceite.setText("- Es preciso cambiar el aceite");
            } else {
                cambioAceite.setText("- No es preciso cambiar el aceite");
            }
        } else {
            cambioAceite.setText("");
        }
    }//GEN-LAST:event_materialButton1ActionPerformed

    public de.craften.ui.swingmaterial.MaterialPanel getPanel() {
        return materialPanel1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.craften.ui.swingmaterial.MaterialButton aceiteButton;
    private de.craften.ui.swingmaterial.MaterialTextField bar;
    private javax.swing.JLabel cambioAceite;
    private javax.swing.JLabel euros;
    private javax.swing.JLabel hinchaRuedas;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private de.craften.ui.swingmaterial.MaterialTextField kms;
    private de.craften.ui.swingmaterial.MaterialButton materialButton1;
    private de.craften.ui.swingmaterial.MaterialPanel materialPanel1;
    private de.craften.ui.swingmaterial.MaterialButton ruedasButton;
    // End of variables declaration//GEN-END:variables
}
