/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aparcamiento.servicios;

/**
 *
 * @author david
 */
public class Reserva extends javax.swing.JDialog {

    private String planta;
    private javax.swing.JButton sel;

    /**
     * Creates new form Registro
     *
     * @param parent
     * @param modal
     * @param sel
     * @param planta
     */
    public Reserva(java.awt.Frame parent, boolean modal, javax.swing.JButton sel, String planta) {
        super(parent, modal);
        this.sel = sel;
        this.planta = planta;
        initComponents();
    }

    public String getTipoPlaza(javax.swing.JButton sel) {
        switch (sel.getMnemonic()) {
            case 0:
                return "Coche ordinario";
            case 1:
                return "Moto";
            case 2:
                return "Movilidad reducida";
            case 3:
                return "Familiar";
        }
        return "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pagoOpc = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        apell = new de.craften.ui.swingmaterial.MaterialTextField();
        jLabel3 = new javax.swing.JLabel();
        email = new de.craften.ui.swingmaterial.MaterialTextField();
        jLabel13 = new javax.swing.JLabel();
        CancelarButton1 = new de.craften.ui.swingmaterial.MaterialButton();
        aceptarButton1 = new de.craften.ui.swingmaterial.MaterialButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setForeground(new java.awt.Color(0, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setMinimumSize(new java.awt.Dimension(340, 290));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setText("Plaza: " + sel.getName() + "     Planta: " + planta);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 250, 33));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Matrícula:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 163, -1, 20));

        apell.setAccent(new java.awt.Color(0, 153, 153));
        apell.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel2.add(apell, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 70, 69));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("Número de horas:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 203, 120, 20));

        email.setAccent(new java.awt.Color(0, 153, 153));
        email.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 30, 69));

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel13.setText("Compruebe los detalles de la reserva:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 290, 33));

        CancelarButton1.setBackground(new java.awt.Color(255, 51, 51));
        CancelarButton1.setText("Cancelar");
        CancelarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(CancelarButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 140, 70));

        aceptarButton1.setBackground(new java.awt.Color(0, 102, 0));
        aceptarButton1.setText("Aceptar");
        aceptarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(aceptarButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 140, 70));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setText("Tipo: " + getTipoPlaza(sel));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 250, 33));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 360, 310));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarButton1ActionPerformed

    private void aceptarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.craften.ui.swingmaterial.MaterialButton CancelarButton1;
    private de.craften.ui.swingmaterial.MaterialButton aceptarButton1;
    private de.craften.ui.swingmaterial.MaterialTextField apell;
    private de.craften.ui.swingmaterial.MaterialTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.ButtonGroup pagoOpc;
    // End of variables declaration//GEN-END:variables
}
